### ISSUE TITLE
Issue with base implementation

### ISSUE THREAD

**Issue by HWideman** [MarshallOfSound/electron-forge-plugin-webpack#1]
I set up a new electron forge project with `--template=react` and the intention to use plugin-webpack to pre-build my react project for electron packaging.

Following the example `react.js` I end up getting an error when running `npm start`:

`App threw an error during load
Error: Cannot find module '<PROJECT ROOT>'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (<PROJECT ROOT>/node_modules/electron-prebuilt-compile/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at init (<PROJECT ROOT>/node_modules/electron-compile/lib/config-parser.js:294:16)
    at main (<PROJECT ROOT>/node_modules/electron-prebuilt-compile/lib/es6-init.js:58:29)
    at Object.<anonymous> (<PROJECT ROOT>/node_modules/electron-prebuilt-compile/lib/es6-init.js:61:1)
    at Object.<anonymous> (<PROJECT ROOT>/node_modules/electron-prebuilt-compile/lib/es6-init.js:63:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)`

Everything else is standard with webpack being configured in forge.config.js

Any tips, or could you possibly upload a more complete example for integration with the react 
electron-forge template?

**Comment by HWideman** [comment]
Upon further review this seems to be an issue when setting:  `"main": ".webpack/main"` in package.json, is there some sort of configuration step I am missing here?

**Comment by MarshallOfSound** [comment]
@HWideman Sorry I probably should have made this more clear in the documentation, this plugin is designed for the upcoming `electron-forge@6`.  See https://github.com/electron-userland/electron-forge/pull/433

It should be released soon~ish and then you can start using this plugin

**Comment by HWideman** [comment]
@MarshallOfSound Thanks, that makes sense! Any tips for implementing webpack with forge in the mean time? Searched and searched, then ended up here haha

**Comment by MarshallOfSound** [comment]
@HWideman It's currently like not a thing, just gotta hold out for v6 😄
