### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by cutterbl** [MarshallOfSound/electron-forge-plugin-webpack#2]
Here's the important snippet from my package.json file. This is in the root of my project.

```
"main": ".webpack/main",
"config": {
  "forge": "forge.config.js"
}
```

And then, in my forge.config.js (also in the project root)

```javascript
const path = require('path');
const WebpackPlugin = require('@electron-forge/plugin-webpack').default;

const sharedModule = {
  rules: [
    {
      test: /\.jsx?$/,
      use: {
        loader: 'babel-loader',
      },
    },
  ],
};

const config = {
  make_targets: {
    win32: [
      'squirrel',
    ],
    darwin: [
      'zip',
    ],
    linux: [
      'deb',
      'rpm',
    ],
  },
  electronPackagerConfig: {
    packageManager: 'yarn',
  },
  electronWinstallerConfig: {
    name: 'karedge',
  },
  electronInstallerDebian: {},
  electronInstallerRedhat: {},
  github_repository: {
    owner: '',
    name: '',
  },
  windowsStoreConfig: {
    packageName: '',
    name: 'karedge',
  },
  plugins: [
    new WebpackPlugin({
      mainConfig: {
        entry: [
          path.resolve(__dirname, 'src/js/main/index.js'),
        ],
        module: sharedModule,
      },
      renderer: {
        config: {
          module: sharedModule,
          resolve: ['.js', '.jsx', '.json'],
        },
        prefixedEntries: process.env.NODE_ENV === 'production' ? [] : ['react-hot-loader/patch'],
        entryPoints: [{
          html: path.resolve(__dirname, 'src/js/renderer/app/index.html'),
          js: path.resolve(__dirname, 'src/js/renderer/app/app.jsx'),
          name: 'main_window',
        }, {
          html: path.resolve(__dirname, 'src/js/background/index.html'),
          js: path.resolve(__dirname, 'src/js/background/background.js'),
          name: 'background_window',
        }],
      },
    }),
  ],
};

module.exports = config;
```

I also have a .babelrc file that mirrors my .compilerc file

```
{
  "env": {
    "development": {
      "application/javascript": {
        "presets": [
          ["env", { "targets": { "electron": "1.6.0" } }],
          "react"
        ],
        "plugins": [
            "transform-async-to-generator",
            "transform-es2015-classes",
            "react-hot-loader/babel"
        ],
        "sourceMaps": "inline"
      }
    },
    "production": {
      "application/javascript": {
        "presets": [
          ["env", { "targets": { "electron": "1.6.0" } }],
          "react"
        ],
        "plugins": [
            "transform-async-to-generator",
            "transform-es2015-classes"
        ],
        "sourceMaps": "none"
      }
    }
  }
}
```

The first issue I ran into was calling `new WebpackPlugin()`, as it kept saying it wasn't a constructor. Tracing the plugin's package.json, through the 'dist/WebpackPlugin.js', I changed my config to use `const WebpackPlugin = require('@electron-forge/plugin-webpack').default;`, and got past that error. Now the error I receive states that electron-compile config-parser can't find my mainModule.

```
Error: Cannot find module '/Users/me/Projects/MyProject'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/Users/stephen.blades/Projects/KarEdge/node_modules/electron-prebuilt-compile/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at init (/Users/stephen.blades/Projects/KarEdge/node_modules/electron-compile/lib/config-parser.js:294:16)
    at main (/Users/stephen.blades/Projects/KarEdge/node_modules/electron-prebuilt-compile/lib/es6-init.js:58:29)
    at Object.<anonymous> (/Users/stephen.blades/Projects/KarEdge/node_modules/electron-prebuilt-compile/lib/es6-init.js:61:1)
    at Object.<anonymous> (/Users/stephen.blades/Projects/KarEdge/node_modules/electron-prebuilt-compile/lib/es6-init.js:63:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
```
My first guess is that electron-compile can not find '/Users/me/Projects/MyProject/.webpack/main', since there doesn't appear to be any such directory/file in my project folder. But, those were the directions, so that's what I tried. Any help in figuring this out would be greatly appreciated.

I'm working with a fresh install of electron-forge (5.2.2) with the latest plugin-webpack (6.0.0-beta.22) on Node 10.9.0 and NPM 6.2.0, on a Mac (10.13.6)

**Comment by MarshallOfSound** [comment]
This repository isn't actually where the webpack plugin lives, it's now in the monorepo in the main `electron-forge` repository.

> I'm working with a fresh install of electron-forge (5.2.2)

You need to be running `@electron-forge/cli` v6.0.0-beta.x to use plugins (including this one).

You should be using forge v6 and follow the webpack docs here --> https://v6.electronforge.io/plugins/webpack
